### ISSUE TITLE
Two questions about this amazing project

### ISSUE THREAD

**Issue by HsnVahedi** [mahieyin-rahmun/NextJsWithDRFExample#4]
Hi, I wish you the best. and Thank you a lot for those two amazing article on medium.com. I just have two questions about that:

1) Why did you disable authentication_classes:

```
class GoogleLoginView(SocialLoginView):
    # disable authentication, make sure to override `allowed origins` in settings.py in production!
    authentication_classes = []
    adapter_class = GoogleOAuth2Adapter
    callback_url = "http://localhost:3000"  # frontend application url
    client_class = OAuth2Clien
```

2) Why didn't you wrap your app like this:

```
function MyApp({ Component, pageProps }) {
  return (
    <Provider session={pageProps.session}>
      <Component {...pageProps} />
    </Provider>
  )
}
```

**Comment by mahieyin-rahmun** [comment]
Hello, I am glad that you found the project useful.

> 1. Why did you disable authentication_classes:
> 
> ```
> class GoogleLoginView(SocialLoginView):
>     # disable authentication, make sure to override `allowed origins` in settings.py in production!
>     authentication_classes = []
>     adapter_class = GoogleOAuth2Adapter
>     callback_url = "http://localhost:3000"  # frontend application url
>     client_class = OAuth2Clien
> ```

This view is responsible for logging the user in. If you do not disable authentication requirements, this view would require authentication to access. At that point, it becomes "you need to be logged in...to log in". Hence, you need to disable the authentication classes for those views so that user can actually make requests to the server to let him log in, provided that he has given valid credentials/data.


> 1. Why didn't you wrap your app like this:
> 
> ```
> function MyApp({ Component, pageProps }) {
>   return (
>     <Provider session={pageProps.session}>
>       <Component {...pageProps} />
>     </Provider>
>   )
> }
> ```

From the `next-auth` [documentation](https://next-auth.js.org/getting-started/client#provider):

> Using the supplied React <Provider> allows instances of useSession() to share the session object across components, **by  using React Context under the hood.** This improves performance, reduces network calls and avoids page flicker when rendering.

So yes, you would be correct that I should have wrapped it around the components, but this does not solve the issue I mentioned in the article about the pitfalls of `useSession()` hook (you may try it out). Now, since I moved away from `useSession()` and used a custom hook to fetch the session, I no longer need to depend on this provider.

However, you can actually store the session in your own custom Context Provider.

```
interface ISessionContextProviderProps {
  refreshInterval?: number;
}

const SessionContext = createContext<{
  session: Session | null;
  loading: boolean;
}>({
  session: null,
  loading: false,
});
export const useSessionContext = () => useContext(SessionContext);

export const SessionContextProvider: React.FC<ISessionContextProviderProps> = ({
  refreshInterval,
  children,
}) => {
  const { session, loading } = useAuth(refreshInterval); // the custom hook I created to fetch session

  return (
    <SessionContext.Provider value={{ session, loading }}>
      {children}
    </SessionContext.Provider>
  );
};
```

Then, you can wrap your components with the above provider:

```
function MyApp({ Component, pageProps }) {
  return (
    <SessionContextProvider>
      <Component {...pageProps} />
    </SessionContextProvider>
  )
}
```

Then, if you ever need to access the `session` object in one of your components, instead of accessing the `session` by `useAuth()` directly, you can call `useSessionContext()`. This is an added level of abstraction which will technically achieve almost the same effect as using `Provider`.

Let me know if you have further queries. Have a good day.
